(maint) Fixes PSSA Failures in DSCResources
The following issues were raised with the updated tests, and needed to be fixed before builds could succeed.

Tests which were mistaken have been overridden at the lowest scope possible. Unused parameters have, in general, been ignored rather than removed to make the smallest amount of change to the actual running code for this.
```
[-] Testing cChoco DSC Resources against PSScriptAnalyzer rule-set.Testing cChocoFeature against default PSScriptAnalyzer rules.Passes 'PSAvoidTrailingWhitespace' 2ms (2ms|0ms)
 Exception: cChocoFeature.psm1:80 Line has trailing whitespace
 cChocoFeature.psm1:134 Line has trailing whitespace
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:42
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:41
[-] Testing cChoco DSC Resources against PSScriptAnalyzer rule-set.Testing cChocoFeature against default PSScriptAnalyzer rules.Passes 'PSReviewUnusedParameter' 2ms (1ms|0ms)
 Exception: cChocoFeature.psm1:139 The parameter 'FeatureName' has been declared but not used. 
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:42
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:41
[-] Testing cChoco DSC Resources against PSScriptAnalyzer rule-set.Testing cChocoInstaller against default PSScriptAnalyzer rules.Passes 'PSAvoidGlobalFunctions' 2ms (1ms|0ms)
 Exception: cChocoInstaller.psm1:125 Avoid creating functions with a Global scope.
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:42
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:41
[-] Testing cChoco DSC Resources against PSScriptAnalyzer rule-set.Testing cChocoInstaller against default PSScriptAnalyzer rules.Passes 'PSReviewUnusedParameter' 2ms (1ms|0ms)
 Exception: cChocoInstaller.psm1:24 The parameter 'InstallDir' has been declared but not used. 
 cChocoInstaller.psm1:72 The parameter 'ChocoInstallScriptUrl' has been declared but not used.
 cChocoInstaller.psm1:131 The parameter 'NoNewLine' has been declared but not used.
 cChocoInstaller.psm1:133 The parameter 'ForegroundColor' has been declared but not used.
 cChocoInstaller.psm1:135 The parameter 'BackgroundColor' has been declared but not used.
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:42
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:41
[-] Testing cChoco DSC Resources against PSScriptAnalyzer rule-set.Testing cChocoPackageInstall against default PSScriptAnalyzer rules.Passes 'PSAvoidGlobalFunctions' 2ms (1ms|0ms)
 Exception: cChocoPackageInstall.psm1:427 Avoid creating functions with a Global scope.
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:42
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:41
[-] Testing cChoco DSC Resources against PSScriptAnalyzer rule-set.Testing cChocoPackageInstall against default PSScriptAnalyzer rules.Passes 'PSAvoidTrailingWhitespace' 2ms (1ms|0ms)
 Exception: cChocoPackageInstall.psm1:286 Line has trailing whitespace
 cChocoPackageInstall.psm1:322 Line has trailing whitespace
 cChocoPackageInstall.psm1:347 Line has trailing whitespace
 cChocoPackageInstall.psm1:350 Line has trailing whitespace
 cChocoPackageInstall.psm1:473 Line has trailing whitespace
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:42
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:41
[-] Testing cChoco DSC Resources against PSScriptAnalyzer rule-set.Testing cChocoPackageInstall against default PSScriptAnalyzer rules.Passes 'PSReviewUnusedParameter' 2ms (1ms|0ms)
 Exception: cChocoPackageInstall.psm1:33 The parameter 'MinimumVersion' has been declared but not used. 
 cChocoPackageInstall.psm1:434 The parameter 'NoNewLine' has been declared but not used.
 cChocoPackageInstall.psm1:436 The parameter 'ForegroundColor' has been declared but not used.
 cChocoPackageInstall.psm1:438 The parameter 'BackgroundColor' has been declared but not used.
 cChocoPackageInstall.psm1:528 The parameter 'NoCache' has been declared but not used.
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:42
 at <ScriptBlock>, C:\tests\Tests\cChoco_ScriptAnalyzer.Tests.ps1:41
```